-- 002_refresh_tokens.sql
--
-- Server-side refresh token storage (Part 6.2), approved in
-- docs/00-README-INDEX.md decision 5.
--
-- Why a table rather than a stateless token: a refresh token has to be
-- revocable. Logout, "log out everywhere", deactivating a user and changing a
-- password all have to invalidate tokens that have not expired yet, and a
-- self-contained signed token cannot be withdrawn once issued.
--
-- The design points worth stating:
--
--   * Only a SHA-256 hash of the token is stored, never the token. A leaked
--     dump of this table must not let anyone authenticate. SHA-256 rather than
--     argon2 here on purpose: the token is 32 bytes of CSPRNG output, so there
--     is no low-entropy guess space for a slow hash to protect, and refresh
--     happens on a hot path.
--
--   * `family_id` groups every token descended from one login. Rotation issues
--     a new token in the same family and marks the old one used. If a token
--     that was already used is presented again, the only explanations are theft
--     or a replay, and the response is to revoke the entire family rather than
--     just that token — otherwise the thief keeps the branch they stole.
--
--   * `used_at` is kept rather than deleting the row. Deleting the old token on
--     rotation would make a replayed token indistinguishable from an expired
--     one, which is exactly the signal this design exists to catch.

-- Up Migration

CREATE TABLE refresh_tokens (
  id            bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id       bigint      NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  -- Every token issued from one login shares this, so theft revokes the chain.
  family_id     uuid        NOT NULL,
  token_hash    text        NOT NULL,
  expires_at    timestamptz NOT NULL,
  -- Set when this token is exchanged; a second use is a replay.
  used_at       timestamptz,
  revoked_at    timestamptz,
  revoked_reason text,
  user_agent    text,
  ip_address    inet,
  created_at    timestamptz NOT NULL DEFAULT now(),

  CONSTRAINT refresh_tokens_token_hash_key UNIQUE (token_hash),
  CONSTRAINT refresh_tokens_expiry_after_creation CHECK (expires_at > created_at)
);

-- The lookup on every refresh: hash to row. Covered by the unique constraint.

-- Revoking a whole family, and revoking every session of one user.
CREATE INDEX refresh_tokens_family_idx ON refresh_tokens (family_id)
  WHERE revoked_at IS NULL;
CREATE INDEX refresh_tokens_user_active_idx ON refresh_tokens (user_id, expires_at DESC)
  WHERE revoked_at IS NULL;

-- The nightly prune of dead rows.
CREATE INDEX refresh_tokens_expires_at_idx ON refresh_tokens (expires_at);

COMMENT ON TABLE refresh_tokens IS
  'Hashed refresh tokens. One row per issued token; family_id groups a login chain so a replayed token can revoke all of its siblings.';

-- Down Migration

DROP TABLE IF EXISTS refresh_tokens;
