-- 006_event_outbox.sql
--
-- Proposal 2 in docs/schema-proposals.md, approved. Required by Module 10 and
-- Phase 5.
--
-- The problem it solves: when a fee payment is recorded, accounting must post a
-- receipt voucher. Doing that inside the payment transaction means an
-- accounting failure rolls back money the school has collected. Doing it after
-- the transaction means a crash in between loses the voucher silently, and the
-- books are wrong with nothing to show why.
--
-- The outbox makes it one transaction: the payment and the intent to post are
-- written together, so either both exist or neither does. A worker then
-- delivers the event and can retry as often as it needs to, because delivery is
-- now separable from the business change.
--
-- `UNIQUE (event_type, source_type, source_id)` is the part that matters most.
-- It makes handlers idempotent at the database level rather than relying on a
-- worker to remember what it has already done: a voucher can be posted at most
-- once per payment, however many times the row is replayed.

-- Up Migration

CREATE TABLE event_outbox (
  id           bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  event_type   text        NOT NULL,

  -- What the event is about. Together these identify the origin, so a handler
  -- can link the voucher back to the payment that caused it.
  source_type  text        NOT NULL,
  source_id    bigint      NOT NULL,

  payload      jsonb       NOT NULL,

  status       text        NOT NULL DEFAULT 'pending',
  attempts     integer     NOT NULL DEFAULT 0,
  last_error   text,

  -- When the worker may next try. Set forward on failure to back off, which is
  -- what stops a permanently broken event being retried in a tight loop.
  available_at timestamptz NOT NULL DEFAULT now(),
  processed_at timestamptz,
  created_at   timestamptz NOT NULL DEFAULT now(),

  CONSTRAINT event_outbox_status_check
    CHECK (status = ANY (ARRAY['pending', 'processing', 'done', 'failed'])),
  CONSTRAINT event_outbox_attempts_check CHECK (attempts >= 0),

  -- Idempotency, enforced by the database.
  CONSTRAINT event_outbox_unique_source UNIQUE (event_type, source_type, source_id)
);

-- The worker's claim query: the oldest due row that is not finished. Partial,
-- so the index stays small as completed events accumulate.
CREATE INDEX event_outbox_claim_idx ON event_outbox (available_at, id)
  WHERE status IN ('pending', 'processing');

-- The dead-letter list (Part 5.9).
CREATE INDEX event_outbox_failed_idx ON event_outbox (created_at DESC)
  WHERE status = 'failed';

-- Tracing an event back from the record it acted on.
CREATE INDEX event_outbox_source_idx ON event_outbox (source_type, source_id);

COMMENT ON TABLE event_outbox IS
  'Transactional outbox. Events are written in the same transaction as the business change; a worker delivers them. UNIQUE(event_type, source_type, source_id) makes replay safe.';

-- Down Migration

DROP TABLE IF EXISTS event_outbox;
